create table employe (emp_id bigint not null auto_increment, email varchar(255), firstname varchar(64), lastname varchar(64), login varchar(255), password varchar(255), phone_number varchar(255), primary key (emp_id)) engine=InnoDB;
create table employe (emp_id bigint not null auto_increment, email varchar(255), firstname varchar(64), lastname varchar(64), login varchar(255), password varchar(255), phone_number varchar(255), primary key (emp_id)) engine=InnoDB;
create table big_data (id bigint not null auto_increment, image longblob, json_data longtext, primary key (id)) engine=InnoDB;
create table client (id bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (id)) engine=InnoDB;
create table client_compte (id_client bigint not null, num_compte bigint not null) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (emp_id bigint not null auto_increment, email varchar(255), firstname varchar(64), lastname varchar(64), login varchar(255), password varchar(255), phone_number varchar(255), primary key (emp_id)) engine=InnoDB;
create table operation (num_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (num_op)) engine=InnoDB;
create table resa_avec_version (id_resa bigint not null auto_increment, num_client bigint, num_version bigint, objet varchar(255), primary key (id_resa)) engine=InnoDB;
alter table client_compte add constraint FKggnv04cd9uupmyr9mxi22c9an foreign key (num_compte) references compte (numero);
alter table client_compte add constraint FKp3pqbm50q2k1b88awdieyhnse foreign key (id_client) references client (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table big_data (id bigint not null auto_increment, image longblob, json_data longtext, primary key (id)) engine=InnoDB;
create table client (id bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (id)) engine=InnoDB;
create table client_compte (id_client bigint not null, num_compte bigint not null) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (emp_id bigint not null auto_increment, email varchar(255), firstname varchar(64), lastname varchar(64), login varchar(255), password varchar(255), phone_number varchar(255), primary key (emp_id)) engine=InnoDB;
create table operation (num_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (num_op)) engine=InnoDB;
create table resa_avec_version (id_resa bigint not null auto_increment, num_client bigint, num_version bigint, objet varchar(255), primary key (id_resa)) engine=InnoDB;
alter table client_compte add constraint FKggnv04cd9uupmyr9mxi22c9an foreign key (num_compte) references compte (numero);
alter table client_compte add constraint FKp3pqbm50q2k1b88awdieyhnse foreign key (id_client) references client (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
