drop table if exists employe;
alter table client_compte drop foreign key FKggnv04cd9uupmyr9mxi22c9an;
alter table client_compte drop foreign key FKp3pqbm50q2k1b88awdieyhnse;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists big_data;
drop table if exists client;
drop table if exists client_compte;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
drop table if exists resa_avec_version;
alter table client_compte drop foreign key FKggnv04cd9uupmyr9mxi22c9an;
alter table client_compte drop foreign key FKp3pqbm50q2k1b88awdieyhnse;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists big_data;
drop table if exists client;
drop table if exists client_compte;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
drop table if exists resa_avec_version;
